### ISSUE TITLE
wrapper can't find files behind a relative symlink

### ISSUE THREAD

**Issue by raybellis** [sweharris/MMB_Utils#1]
If you use a relative symlink instead of an absolute one for `beeb` it can't find itself.

The fix is to replace `$FindBin::Bin` with `$FindBin::RealBin`.

I'm running on macOS and didn't want to pollute `/usr/local`, so I did:

```
% mkdir ~/bin/.beeb
% cd !$
% tar xf ~/Downloads/MMB_Utils.tar
% cd ..
% ln -s .beeb/beeb .
```

**Comment by sweharris** [comment]
Ah!  I hadn't hit this in testing 'cos all my relative tests had used "./beeb" to run the command.

Thanks.

Fixed!
