### ISSUE TITLE
list command doesn't correctly deal with Z80 basic files

### ISSUE THREAD

**Issue by hoglet67** [sweharris/MMB_Utils#3]
It seems the -t variant option changes the token definitions.

That's not actually sufficient, as the line structure is different in Z80 BBC Basic.

6502 BBC Basic uses the following structure:
```
0x0d [line num hi] [line num lo] [line len] [data...]
...
0x0d 0xff
```

Z80 BBC Basic is slightly different:
```
[line len] [line num lo] [line num hi]  [data...] 0x0d
...
0x00 0xff 0xff
```
There are some samples here:
https://github.com/davidgiven/cpmish/tree/master/third_party/bbcbasic/examples

Here's the start of animal.bbc:
```
pi@pi4hog:~/tmp $ hexdump -C animal.bbc | head
00000000  1e 0a 00 db 3a 40 25 3d  31 30 3a fe 20 30 3a f1  |....:@%=10:. 0:.|
00000010  20 8a 31 35 29 22 41 4e  49 4d 41 4c 22 0d 32 14  | .15)"ANIMAL".2.|
00000020  00 f1 20 22 43 72 65 61  74 69 76 65 20 43 6f 6d  |.. "Creative Com|
00000030  70 75 74 69 6e 67 20 4d  6f 72 72 69 73 74 6f 77  |puting Morristow|
00000040  6e 20 4e 65 77 20 4a 65  72 73 65 79 22 27 27 0d  |n New Jersey"''.|
00000050  28 1e 00 f4 20 62 79 20  4e 61 74 68 61 6e 20 54  |(... by Nathan T|
00000060  65 69 63 68 68 6f 6c 74  7a 20 26 20 53 74 65 76  |eichholtz & Stev|
00000070  65 20 4e 6f 72 74 68 0d  30 28 00 f4 20 66 72 6f  |e North.0(.. fro|
00000080  6d 20 61 6e 20 6f 72 69  67 69 6e 61 6c 20 69 64  |m an original id|
00000090  65 61 20 62 79 20 41 72  74 68 75 72 20 4c 75 65  |ea by Arthur Lue|
```

**Comment by hoglet67** [comment]
Richard's documentation of this format is here:
https://www.bbcbasic.co.uk/bbcbasic/mancpm/annexd.html#programstorage

I suspect this applies to BBC Basic for Windows files as well as Z80.

**Comment by sweharris** [comment]
Thanks.  I'll take a look at this.

Hmm, BBC B4W may have the added "line number 0" is a numberless line issue, but I think I can work with that as well.

**Comment by sweharris** [comment]
I've pushed to a branch "z80" code that I think will handle z80 and b4w formats....

```
% beeb list animal.bbc -t z80 | head
   10CLS:@%=10:WIDTH 0:PRINT TAB(15)"ANIMAL"
   20PRINT "Creative Computing Morristown New Jersey"''
   30REM by Nathan Teichholtz & Steve North
   40REM from an original idea by Arthur Luehrmann.
   50REM Modified by Chris Atkinson and Richard Russell.
   60:
   70ON ERROR IF ERR=17 THEN 830 ELSE PRINT:REPORT:PRINT" at line ";ERL:END
   80MAX=(HIMEM-TOP)/40
   90DIM A$(MAX)
  100PRINT "Play 'Guess the Animal'"
```

Could you perform some testing  at your end and see if it looks good, or if you find some oddities?

Thanks!

**Comment by hoglet67** [comment]
That works with the BBC Basic example I was looking at previously (which came from the Agon Light people).

Thanks

Dave
